empty_item_single_line = true
enum_discrim_align_threshold = 50
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
max_width = 90
preserve_block_start_blank_lines = true # doesn't seem to work @@@
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
