max_width = 90
use_field_init_shorthand = true

# These currently work only on nightly

empty_item_single_line = true
enum_discrim_align_threshold = 50
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
reorder_impl_items = true
wrap_comments = true
