name: "CI checks"
on: [push, pull_request]
jobs:
  # note - there aren't any tests to run here

  # cargo check
  check:
    name: basic checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  # rustfmt and clippy. This is done in a special way to use the
  # additional features of nightly, but without failing when those
  # aren't available - see
  # https://github.com/actions-rs/meta/blob/master/recipes/nightly-lints.md
  fmt-clippy:
    name: rustfmt + clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
